#pragma once
#include "../Image/Image.h"
#include "../Linalg.h"
#include "../Object/Object.h"
#include "../Scene/Camera.h"
#include "../Scene/World.h"
#include <algorithm>
#include <queue>
#include <stdexcept>
#include <vector>
